version: '3'
services:
  webapp:
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./webapp:/usr/src/app
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    image: webapp-image
    container_name: webapp-container
    command: >
      bash -c "python ./manage.py migrate --noinput &&
               python ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
      MYSQL_HOST: ${db_host}
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: nginx-image
    container_name: nginx-container
    ports:
      - 80:80
    depends_on:
      - webapp
    links:
      - webapp
    entrypoint:
      - /docker-entrypoint.sh
    volumes:
      - ./logs:/var/log/nginx

