# Generated by Django 4.1 on 2022-09-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-cnt'], 'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
