# Generated by Django 4.1 on 2022-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
