# Generated by Django 4.1 on 2022-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_visit_product_by_user'),
        ),
    ]
