# Generated by Django 4.1 on 2022-09-27 06:51

from django.db import migrations, models

import accounts.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.user.profile_img_upload_path,
                verbose_name="프로필 이미지",
            ),
        ),
    ]
