# Generated by Django 4.1 on 2022-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
