# Generated by Django 4.1 on 2022-12-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agree_personal_optional",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
