# Generated by Django 4.1 on 2022-11-21 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_visit_product_by_user'),
        ),
    ]
