# Generated by Django 4.1 on 2022-09-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_id_alter_code_name_and_more'),
        ('accounts', '0003_visit_unique_visit_product_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='product.product'),
        ),
    ]
