# Generated by Django 4.1 on 2022-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_age_user_gender_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="",
                error_messages={"unique": "A user with that nickname already exists."},
                max_length=100,
                unique=True,
            ),
        ),
    ]
