# Generated by Django 4.1 on 2022-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="introduce",
            field=models.CharField(
                blank=True,
                default="사용자 소개가 없습니다.",
                max_length=300,
                null=True,
                verbose_name="사용자 소개",
            ),
        ),
    ]
