# Generated by Django 4.1 on 2022-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_introduce"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agree_personal_optional",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="agree_personal_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="agree_prefragrance",
            field=models.BooleanField(default=True),
        ),
    ]
