# Generated by Django 4.1 on 2022-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewtag',
            constraint=models.UniqueConstraint(fields=('review', 'tag'), name='unique_review_tag'),
        ),
    ]
