# Generated by Django 4.1 on 2022-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="season",
            field=models.CharField(
                choices=[
                    ("SPRING", "Spring"),
                    ("SUMMER", "Summer"),
                    ("AUTUMN", "Autumn"),
                    ("WINTER", "Winter"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="time",
            field=models.CharField(
                choices=[("DAY", "Day"), ("NIGHT", "Night")], max_length=100
            ),
        ),
    ]
