# Generated by Django 4.1 on 2022-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_season_alter_review_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_medal', models.IntegerField()),
                ('silver_medal', models.IntegerField()),
                ('bronze_medal', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Review Count',
                'verbose_name_plural': 'Review Counts',
                'db_table': 'review_count',
            },
        ),
    ]
