# Generated by Django 4.1 on 2022-09-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_search_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendSearch',
        ),
        migrations.DeleteModel(
            name='UserProductSearch',
        ),
    ]
