# Generated by Django 4.1 on 2022-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_delete_recommendsearch_delete_userproductsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'RecommendSearch',
                'verbose_name_plural': 'RecommendSearches',
                'db_table': 'recommend_searches',
            },
        ),
    ]
