# Generated by Django 4.1 on 2022-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_recommendsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SearchLog',
                'verbose_name_plural': 'SearchLogs',
                'db_table': 'search_logs',
            },
        ),
    ]
