# Generated by Django 4.1 on 2022-11-21 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('producer', models.CharField(max_length=400)),
                ('feedback_cnt', models.IntegerField(default=0)),
                ('review_cnt', models.IntegerField(default=0)),
                ('visit_cnt', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('rate_sum', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='codes',
            field=models.ManyToManyField(related_name='codes', through='product.ProductCode', to='product.code'),
        ),
        migrations.AddField(
            model_name='product',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_products', through='product.ProductFeedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='productfeedback',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique productfeedbacks'),
        ),
        migrations.AddConstraint(
            model_name='productcode',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_product_code'),
        ),
    ]
